<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>fbbde41c-45e5-4e2a-b800-a8f2eb4c00af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/section/div/div[4]/div/div[3]/a/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Version 8.4 November 2024 Efficient Asset Management and Financial Solutions for Logistics Learn More Card Logo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>61071ea1-88a7-4680-a188-a9f488eb7793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://lcsbridge.com/blog/wp-content/uploads/2024/11/version-8.4.png</value>
      <webElementGuid>8823e9ad-1cb6-4dfc-a263-ad5da3d28929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Card Logo</value>
      <webElementGuid>15bfdadf-d1fe-4549-8201-85f0bc5013b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>245ab1a2-2fcf-471d-96ac-4cd43142f19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;container-fluid py-3&quot;]/section[@class=&quot;version-content&quot;]/div[@class=&quot;px-5 mt-4&quot;]/div[@class=&quot;my-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-sm-12&quot;]/a[1]/div[@class=&quot;bg-primary-v5 round old-feature px-3 pt-3 d-flex flex-column&quot;]/div[@class=&quot;mt-3 mt-auto old-version-img&quot;]/img[1]</value>
      <webElementGuid>509f6486-b3b7-4808-8e9f-900af2eff528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section/div/div[4]/div/div[3]/a/div/div[2]/img</value>
      <webElementGuid>59b47c82-186f-4689-ad0c-ca184e62e85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Card Logo'])[2]</value>
      <webElementGuid>6bb4941f-913c-49b3-af0a-eee4a5111f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/div[2]/img</value>
      <webElementGuid>a426124a-9049-4725-b4af-b32ba34978ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://lcsbridge.com/blog/wp-content/uploads/2024/11/version-8.4.png' and @alt = 'Card Logo']</value>
      <webElementGuid>40d50ade-8c59-402d-9a93-256ed1fc09a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
