<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select1 Week15 Days30 Days60 Days90 _89f8ad</name>
   <tag></tag>
   <elementGuidId>272af483-3a5c-4462-8417-25bdeadbc068</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='credit-period']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#credit-period</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#credit-period</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8ffb1652-8150-482b-a612-697f5ff33c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control selectpicker credit-period</value>
      <webElementGuid>9881341d-c51c-4c8f-aa25-0e649529d9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>credit-period</value>
      <webElementGuid>e5f41b3c-c3ea-4f1f-8b26-87d137318095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>credit_period</value>
      <webElementGuid>cbc8eda1-c601-4ba0-a9de-8976e70b116d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-98</value>
      <webElementGuid>ba8759ef-d174-41cf-a721-c7d85032db46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5d70400a-4169-4aae-84d4-880b6564d110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select1 Week15 Days30 Days60 Days90  DaysCustom</value>
      <webElementGuid>59b4b01d-c5a9-4064-bd6a-750b4b42835c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credit-period&quot;)</value>
      <webElementGuid>60e043ea-3ef1-46a7-bc58-7aa71c309cd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='credit-period']</value>
      <webElementGuid>683e5ec8-cd14-4faa-9068-1b61372cc572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sales-row']/div[4]/div/div/select</value>
      <webElementGuid>c711eca0-ab47-4ed3-b911-8316c2527c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Limit'])[1]/following::select[1]</value>
      <webElementGuid>e8be96de-9924-41fc-8dd6-326b7d86dfc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Referral'])[1]/following::select[1]</value>
      <webElementGuid>94b532f1-5282-48b3-8c98-7fc3a900d406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[11]/preceding::select[1]</value>
      <webElementGuid>b592bd2f-3b7b-42a1-8b2c-fc5163f28a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Period'])[1]/preceding::select[1]</value>
      <webElementGuid>c769303d-bffe-460c-9163-bbc8926b3e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[4]/div/div/select</value>
      <webElementGuid>86657805-8e7c-4ff1-81cc-635c95ba943c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'credit-period' and @name = 'credit_period' and (text() = 'Select1 Week15 Days30 Days60 Days90  DaysCustom' or . = 'Select1 Week15 Days30 Days60 Days90  DaysCustom')]</value>
      <webElementGuid>0151a28a-357f-40b7-8a03-7bba726adf94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
