<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Supplier Name In Local Language_notif_7bba5b</name>
   <tag></tag>
   <elementGuidId>194b96be-c34d-4719-a30d-7a7b7d972801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notifying-person</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notifying-person']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Notifying Person&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dae51f20-d64b-4c6d-a278-0b631d47effe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d2c1586-c345-4ace-a1be-70877fbf0d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notifying-person</value>
      <webElementGuid>45b9a8c7-66ac-45ec-84fe-fcbdca919e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notifying_person</value>
      <webElementGuid>3807cd92-c04d-49ac-937c-322930eeed3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control typeahead</value>
      <webElementGuid>903be728-70da-432e-bc1f-253e5b0f3322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>6fc3f2f4-1aa9-4223-9f3e-67cb0116e28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-model</name>
      <type>Main</type>
      <value>Supplier\Supplier</value>
      <webElementGuid>2f35135a-a286-4475-ab3d-8e3f413b95da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>notifying_person</value>
      <webElementGuid>de988d3a-9793-49b9-bf94-5eaab4bea33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notifying-person&quot;)</value>
      <webElementGuid>5d525325-9a4e-4ba5-83bd-7a7bc3274236</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notifying-person']</value>
      <webElementGuid>b3ca2688-613c-49f0-b4ae-0e6aaf1023e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gen']/div/div/div[3]/div/input</value>
      <webElementGuid>03c3984e-8348-41ae-9272-d174ea653779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>4c308f29-12ab-4eb0-ae22-512d79a7afb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'notifying-person' and @name = 'notifying_person']</value>
      <webElementGuid>f3701249-50eb-452b-b13b-967680ad585f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
