<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Salesman_address_1</name>
   <tag></tag>
   <elementGuidId>2e1f022a-51a7-4cd4-bd8c-0175f76303ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#address-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='address-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Street 1&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1c0d0a67-ad0b-468b-bbd2-af34a7b11690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>303d876d-2116-45c3-ab35-5dadb25e5bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>364113bc-8ef2-4f2f-8914-0c94683eb5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>26040efa-97fa-41f7-92dc-b402af945c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>225</value>
      <webElementGuid>f9a37758-ca97-4a8c-af09-ef4426054d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address_1</value>
      <webElementGuid>65b57d8b-c2d3-4a94-991d-cc26bfc4cb4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>address-1</value>
      <webElementGuid>091e90d0-9676-4f49-8bee-ff0638d9fb55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cea61f6e-c857-489a-85e4-1b3aed71e604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;address-1&quot;)</value>
      <webElementGuid>9e3ab9c0-112a-499f-9a9c-52c6c3c965a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='address-1']</value>
      <webElementGuid>12b04ffc-bc71-4270-a3f0-eea60ffe64c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact']/div/div/div/textarea</value>
      <webElementGuid>a9ab6d14-9251-480e-9c5f-ea624f8dc1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>52a56c70-8a77-473b-94a0-0d4df5b68f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'address_1' and @id = 'address-1']</value>
      <webElementGuid>415f6906-7d0d-45f2-8a02-ae67f1a84873</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
