<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_aaaaaaaaaaaaaaq_price0</name>
   <tag></tag>
   <elementGuidId>a9e7313f-20c8-4fd0-999b-d1e97cf91890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='price[0]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;price[0]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;9.00&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f412fc2-7a70-426d-9bbc-de460f902e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control price-input price cell-amount currency tab-row</value>
      <webElementGuid>85cb153b-fe82-4fe1-bd51-1e3344f3604a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>ae7510de-6398-425b-a694-457b5701e946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-changed</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f6bd2d33-edc8-4794-b6a0-b0468e666d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>price[0]</value>
      <webElementGuid>91e02a86-99be-4496-a6ec-d2945b103e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>173e143a-88c3-46a1-bd36-5f8157c9e9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>9.00</value>
      <webElementGuid>19ab17ff-8caa-4bd5-855d-25bb0a4366f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;&quot;invoice-row&quot;&quot;)/td[@class=&quot;form-group&quot;]/input[@class=&quot;form-control price-input price cell-amount currency tab-row&quot;]</value>
      <webElementGuid>1d834593-3d31-4eb2-83ee-c2a58df530e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='price[0]']</value>
      <webElementGuid>3bb44fff-0dbf-4130-8a0c-d09ed39cf008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='&quot;invoice-row&quot;']/td[7]/input</value>
      <webElementGuid>52a259e2-32da-44bf-b69b-7e0baa98518d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/input</value>
      <webElementGuid>84d6ca9e-7305-402f-a531-aabb38081727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'price[0]' and @type = 'text' and @placeholder = '9.00']</value>
      <webElementGuid>a63b8765-d6a9-40a0-8a10-c50591d456bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
