<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Approve</name>
   <tag></tag>
   <elementGuidId>26af2b63-3327-42cd-9548-04099f77b6ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='data_approve']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#data_approve</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Approve&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3244ae2a-cc6c-4ef0-9711-7fefaf609b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>1e18f041-da40-4bec-97fe-9df4cd7a14a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Approve</value>
      <webElementGuid>5e5c79a6-5d4f-4dab-b16b-d08c2e7276a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data_approve</value>
      <webElementGuid>93de293c-80cc-472f-a01a-aaace18adb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>code</name>
      <type>Main</type>
      <value>34SLAP</value>
      <webElementGuid>a0d03b13-3b67-4963-b363-7aca34d00e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e6ebf92f-80bc-4dee-bd17-937b481b5e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-invoiced</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>672decf5-e0b4-49c9-a7c9-49eb6ea9448e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-approve</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6886850c-e670-4f61-87d3-1ea0b98f92f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bill</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>45fcf404-ba23-4353-b3aa-0b6cba7368c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-job</name>
      <type>Main</type>
      <value>6867953353489453</value>
      <webElementGuid>47398bff-25f2-43b2-8081-5a51e0bcbf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-scanned-invoice</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fe1a0a5c-4327-4fc9-928b-f32d500be3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-invoice</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a7280ce3-c071-4251-a2d1-40ec5d887118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve</value>
      <webElementGuid>37c3eb80-2bad-4a87-927c-fa2cb8b1b04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data_approve&quot;)</value>
      <webElementGuid>0d010a95-cd77-40b3-a382-a1834a96b1f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='data_approve']</value>
      <webElementGuid>7d82b24a-fbce-4129-b1c3-1824d1917914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='context-dropdown']/span</value>
      <webElementGuid>984788d4-5f7e-4f2b-ad23-2b2818307e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SI250057'])[2]/following::span[1]</value>
      <webElementGuid>38d5e811-549b-44f2-a8d6-f3fcac92e216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audio message'])[1]/following::span[12]</value>
      <webElementGuid>71259993-e1c7-4ef6-ba20-a97a95a51847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Replicate'])[1]/preceding::span[1]</value>
      <webElementGuid>bdb4aecb-2dab-49e9-9806-14895bd6a1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print'])[1]/preceding::span[2]</value>
      <webElementGuid>c7d591c7-49c0-4786-9ce8-56aa2a199f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Approve']/parent::*</value>
      <webElementGuid>444ecd8c-dad0-4676-9fa7-40fb71dc677f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span</value>
      <webElementGuid>5d2c6b18-06dd-4f1a-8d36-1f817f17df81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@name = 'Approve' and @id = 'data_approve' and (text() = 'Approve' or . = 'Approve')]</value>
      <webElementGuid>e3a915ff-71ad-4a79-a414-258946fafef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SI250056'])[2]/following::span[1]</value>
      <webElementGuid>4ef924e3-6557-4277-a291-49df267834a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
