<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TKtest kirantest kiran SP250005Malappu_43872d</name>
   <tag></tag>
   <elementGuidId>3cd7694e-f467-4547-8557-c18696aa2ac8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-2-0']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-2-0 > span.text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;TK test kiran SP250005 Malappuram, India&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e6b5ce0-5e8c-41c4-be6a-e1338160df3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2491d2c8-78e1-474f-ae97-572f4912f71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TKtest kirantest kiran SP250005Malappuram, India</value>
      <webElementGuid>a3a090c9-81d2-427e-bcfa-0172a6f9cf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-2-0&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>ed9aa707-20aa-4eac-ac15-5ace5633f5af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-2-0']/span</value>
      <webElementGuid>e2479f6a-d02d-43bf-9418-990525f9d773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::span[1]</value>
      <webElementGuid>40dcf9c9-8097-42cc-b11b-90ebaa989457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::span[1]</value>
      <webElementGuid>23d9f652-b84e-428a-8ead-2bbff5147688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/ul/li/a/span</value>
      <webElementGuid>5814f4fe-a112-4989-899b-d3f9ad58ec67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TKtest kirantest kiran SP250005Malappuram, India' or . = 'TKtest kirantest kiran SP250005Malappuram, India')]</value>
      <webElementGuid>eceb2b10-f29d-4f78-8874-f07554b5aeaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
