<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Air Local Trop                           _7478bf</name>
   <tag></tag>
   <elementGuidId>3c7f7934-d2fa-48ef-afdf-889a66432004</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-8-12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-8-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Air Local Trop Air&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ac7f4dd-f495-4c51-9e5e-2975069c3bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>68024164-1857-4e92-af55-ee889ec5efc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>opt dropdown-item</value>
      <webElementGuid>3bc127ab-3e99-42bb-b374-69e94ab40916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bs-select-8-12</value>
      <webElementGuid>88aeb3f4-6fdf-4248-87f8-c155fefd8ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de6b1bda-8427-484b-8191-5f1d7bc35510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>51</value>
      <webElementGuid>3f72abb1-ee75-4cc3-8589-37532b48331f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>133d0aae-36e7-4499-81cd-6c251eff6448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Air Local Trop
                                        Air</value>
      <webElementGuid>eb0eccbe-c552-40fc-ac92-fd98c9f648ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-8-12&quot;)</value>
      <webElementGuid>1b96c936-bd39-4c40-90f8-2cb6b18c47ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bs-select-8-12']</value>
      <webElementGuid>910ba6fd-ba49-4ca2-b5a1-34ee177fd422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-select-8']/ul/li[13]/a</value>
      <webElementGuid>baaf04b4-37d9-4536-b96e-9abc945be967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Air'])[3]/following::a[1]</value>
      <webElementGuid>38ead612-1457-4993-bca0-2133a2b1dafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/ul/li[13]/a</value>
      <webElementGuid>7181a43f-19cf-42f0-816b-4281ef5ff0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bs-select-8-12' and (text() = '
                                            Air Local Trop
                                        Air' or . = '
                                            Air Local Trop
                                        Air')]</value>
      <webElementGuid>555f7714-f2b9-4221-9683-6f4a8e0c5996</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
