<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Rishi_3c275a45                           _7bccf1</name>
   <tag></tag>
   <elementGuidId>0125857f-b44b-452b-9922-85c6e19d2ae7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-6-4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bs-select-6-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Rishi_3c275a45 CR250042&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>77c6363c-f8d6-4dfd-b653-6421b28fefeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>028af04d-ea81-4fd1-a370-d2ddef6d8c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>e14581b2-a13b-40ae-9f40-7967e03adaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bs-select-6-4</value>
      <webElementGuid>0a2920c8-061f-408b-8334-e70457e8d21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>073eaae1-b646-4479-974c-b5b2a73e113e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-setsize</name>
      <type>Main</type>
      <value>1147</value>
      <webElementGuid>c4671c9b-12da-4087-8e42-7852870688ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-posinset</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>bac56a58-96d6-46a9-8652-73fb8c1ef3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Rishi_3c275a45
                                CR250042</value>
      <webElementGuid>2b3fedc8-69e2-40ef-b6af-aae10ce18b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-6-4&quot;)</value>
      <webElementGuid>5b8a3223-47db-4f0b-b2f4-84b53e38b73c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='bs-select-6-4']</value>
      <webElementGuid>018a63e9-104b-41a0-bbaa-051e4da1ce7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bs-select-6']/ul/li[5]/a</value>
      <webElementGuid>428f66d2-f3d9-46fb-8dbb-f8da2364962f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CR250043'])[1]/following::a[1]</value>
      <webElementGuid>2be44da2-b12b-47fe-b6ca-a26d7c018fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/ul/li[5]/a</value>
      <webElementGuid>5e927d06-d3aa-4b81-9d8e-e4b4340d7fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'bs-select-6-4' and (text() = '
                                    Rishi_3c275a45
                                CR250042' or . = '
                                    Rishi_3c275a45
                                CR250042')]</value>
      <webElementGuid>3a0ccbf1-edf9-4489-872f-9c2494a042ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
