<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select_1_2</name>
   <tag></tag>
   <elementGuidId>29690fd4-b91e-41fb-887f-6708bde9c997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[68]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown.bootstrap-select.show-tick.form-control.change_service.dropup > button.btn.dropdown-toggle.bs-placeholder.btn-material.bs-selectpicker</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#job-general div >> internal:has-text=&quot;General RishiUser_37ab1130 RishiUser_22074361 RishiUser_88a07f39 Rishi_2a72affc &quot;i >> internal:attr=[title=&quot;Select&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2992cc67-38d5-4219-9b58-a43ff30bae69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee3e3f69-8096-48b1-81b1-25b8bd88e756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dropdown-toggle bs-placeholder btn-material bs-selectpicker</value>
      <webElementGuid>cb6fd771-eda3-4da5-818f-d1152815a68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>ce0f22ac-691d-40bf-bee1-4ac8b0100a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>77c3e6ac-4dea-48ce-a490-50f30ce88e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>bs-select-9</value>
      <webElementGuid>99d90e44-d877-4486-bfbf-83d0ddf6bf05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>cd774e26-cf5a-4686-899a-0d6060d9a092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc1f478e-bfcd-4cfd-ac06-4a8d764e9372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>service</value>
      <webElementGuid>1dd25bfb-cf5d-4573-a7af-5a02f82b3549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>9265ea56-3e44-4591-86d9-325ed0443500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select </value>
      <webElementGuid>fc242d23-165c-4390-9a09-e2f174aa6b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job-general&quot;)/div[@class=&quot;float-title-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-4 col-lg-4 col-6&quot;]/div[@class=&quot;form-group validate&quot;]/div[@class=&quot;dropdown bootstrap-select show-tick form-control change_service dropup&quot;]/button[@class=&quot;btn dropdown-toggle bs-placeholder btn-material bs-selectpicker&quot;]</value>
      <webElementGuid>0f2e82ab-1eb9-47d3-8989-49b60403fb36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[68]</value>
      <webElementGuid>af9e952d-2513-4ccc-8a37-5aa38b14ab00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='job-general']/div/div/div[5]/div/div/button</value>
      <webElementGuid>3728bf19-20ea-4691-b883-a63bed57c6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Stages'])[1]/following::button[1]</value>
      <webElementGuid>a521707f-60dd-4706-bd63-1d88d705a809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customs Clearance'])[2]/preceding::button[1]</value>
      <webElementGuid>f0aa1b65-4363-426f-9488-a223a2a660b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[5]/div/div/button</value>
      <webElementGuid>2dcb5251-4e95-4695-b903-1fee4643928a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Select' and (text() = 'Select ' or . = 'Select ')]</value>
      <webElementGuid>87701c8d-04da-4a1c-a0c7-749e236c4825</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
