<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select</name>
   <tag></tag>
   <elementGuidId>cc70b827-93c7-49eb-b805-e0abbdc35f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[65]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown.bootstrap-select.form-control.customer-id > button.btn.dropdown-toggle.btn-material.bs-selectpicker.bs-placeholder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.col-xl-4 > .form-group > .dropdown > .btn >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b0d257e-3fd0-4e4e-9748-745aec2c875b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b001bc30-a1d0-4b6d-8dce-47cf4caa379d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dropdown-toggle btn-material bs-selectpicker bs-placeholder</value>
      <webElementGuid>f79a2350-753e-40dc-bfad-40ea8cf9873a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>70261886-e510-403e-9a20-7adc399e71e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>48cd22c0-b171-46c7-9b67-b135ede8f9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>bs-select-6</value>
      <webElementGuid>acbc52a2-e3ac-40ae-88d2-f52439ed3ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>306fb101-f4d0-4034-aa8f-75c5601ca06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>532ef5aa-b75f-4d30-9f22-acc523e1c5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>customer-id</value>
      <webElementGuid>651b3860-c77f-4d0e-a51f-7b32ce4faaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>f9f5e4e6-28f6-4c09-820d-df749e16faa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select </value>
      <webElementGuid>7bead67c-f7e5-4bab-aab5-f180dd794df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job-general&quot;)/div[@class=&quot;float-title-box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-4 col-lg-4 col-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;dropdown bootstrap-select form-control customer-id&quot;]/button[@class=&quot;btn dropdown-toggle btn-material bs-selectpicker bs-placeholder&quot;]</value>
      <webElementGuid>d16dcb0c-1409-47bf-b664-5d1b9741d963</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[65]</value>
      <webElementGuid>e594d158-8ed8-4e6e-af40-0975a35fc9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='job-general']/div/div/div/div/div/button</value>
      <webElementGuid>7bdd039e-aec2-4362-a5c7-9a86b82ef17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[3]/following::button[1]</value>
      <webElementGuid>70ded24d-e4de-4b83-94c7-9af48667fd8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import'])[2]/following::button[1]</value>
      <webElementGuid>2cabf647-d2f6-4b53-9d27-bbb292309963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary Customer'])[1]/preceding::button[1]</value>
      <webElementGuid>7bd5a0b0-698f-4cf0-8f20-04037b70f0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/div/div/div/button</value>
      <webElementGuid>d4764de2-94f4-4274-ab9d-24dd8dda526e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Select' and (text() = 'Select ' or . = 'Select ')]</value>
      <webElementGuid>6475b81b-1cd8-4227-a0b8-207563d3d68c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
